export const UPDATE_PROJECT_NAME = "UPDATE_PROJECT_NAME";
export const UPDATE_PROJECT_DESCRIPTION = "DESCRIPTION";
export const REMOVE_PROJECT_MEMBERS = "REMOVE_PROJECT_MEMBERS";
export const ADD_PROJECT_MEMBERS = "ADD_PROJECT_MEMBERS";
export const UPDATE_PROJECT_START_DATE = "UPDATE_PROJECT_START_DATE";
export const UPDATE_PROJECT_END_DATE = "UPDATE_PROJECT_END_DATE";

export const SHOW_PROJECTS = "SHOW_PROJECTS"